/**
 * Get Module Federation exposes configuration
 *
 * This generates exposes from federation.config.js and ensures wrapper files exist.
 * Called during nuxt.config.js evaluation (before webpack starts).
 */
const fs = require('fs')
const path = require('path')

function capitalize(str) {
  // Handle kebab-case: stats-card -> StatsCard
  return str.split('-').map(part => part.charAt(0).toUpperCase() + part.slice(1)).join('')
}

/**
 * Generate wrapper code for a page or component
 */
function generateWrapperCode(rootDir, moduleName, sourcePath, defaults = {}) {
  const elementName = `legacy-${moduleName}`

  // Try to load co-located config
  let moduleConfig = {}
  const configPaths = [
    path.join(rootDir, `${sourcePath}.federation.js`),
    path.join(rootDir, sourcePath, 'index.federation.js')
  ]

  for (const configPath of configPaths) {
    if (fs.existsSync(configPath)) {
      delete require.cache[require.resolve(configPath)]
      moduleConfig = require(configPath)
      break
    }
  }

  // Merge defaults with module-specific config
  const finalConfig = {
    events: moduleConfig.events || defaults.events || ['state:changed'],
    injectSharedState: moduleConfig.injectSharedState ?? defaults.injectSharedState ?? false,
    enableEventLog: moduleConfig.enableEventLog ?? defaults.enableEventLog ?? false,
    eventHandlers: moduleConfig.eventHandlers || {},
    props: moduleConfig.props || []
  }

  // Determine the import path
  const importPath = `~/${sourcePath}.vue`

  // Generate the wrapper code
  return `/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by modules/federation for: ${sourcePath}
 */
import { createWrapper } from '../createWrapper.js'
import Component from '${importPath}'

const options = ${JSON.stringify(finalConfig, null, 2).replace(/"([^"]+)":/g, '$1:')}

options.elementName = '${elementName}'

export default createWrapper(Component, options)
`
}

function getExposes(rootDir) {
  // Load config from shared package
  const sharedConfigPath = path.join(rootDir, '../../packages/shared/federation.config.js')

  if (!fs.existsSync(sharedConfigPath)) {
    console.warn('[Federation] No shared/federation.config.js found')
    return {}
  }

  delete require.cache[require.resolve(sharedConfigPath)]
  const config = require(sharedConfigPath)

  const generatedDir = path.join(rootDir, 'remote-entries', '.generated')

  // Ensure generated directory exists
  if (!fs.existsSync(generatedDir)) {
    fs.mkdirSync(generatedDir, { recursive: true })
  }

  const exposes = {}
  const moduleMap = {}

  // Generate page wrappers
  if (config.pages) {
    Object.entries(config.pages).forEach(([moduleName, pageConfig]) => {
      // Support both old format (string) and new format (object with source)
      const pagePath = typeof pageConfig === 'string' ? pageConfig : pageConfig.source
      const fileName = `${capitalize(moduleName)}Page.js`
      const filePath = path.join(generatedDir, fileName)

      // Generate wrapper file
      const code = generateWrapperCode(rootDir, moduleName, pagePath, config.defaults)
      fs.writeFileSync(filePath, code)

      // Build exposes map
      exposes[`./${capitalize(moduleName)}Page`] = `./remote-entries/.generated/${fileName}`

      // Build module map
      moduleMap[moduleName] = {
        path: `./${capitalize(moduleName)}Page`,
        elementName: `legacy-${moduleName}`
      }
    })
  }

  // Generate component wrappers
  if (config.components) {
    Object.entries(config.components).forEach(([moduleName, componentConfig]) => {
      // Support both old format (string) and new format (object with source)
      const componentPath = typeof componentConfig === 'string' ? componentConfig : componentConfig.source
      const fileName = `${capitalize(moduleName)}Component.js`
      const filePath = path.join(generatedDir, fileName)

      // Generate wrapper file
      const code = generateWrapperCode(rootDir, moduleName, componentPath, config.defaults)
      fs.writeFileSync(filePath, code)

      exposes[`./${capitalize(moduleName)}Component`] = `./remote-entries/.generated/${fileName}`
      moduleMap[moduleName] = {
        path: `./${capitalize(moduleName)}Component`,
        elementName: `legacy-${moduleName}`
      }
    })
  }

  // Write manifest for reference
  const manifestPath = path.join(generatedDir, '_manifest.json')
  fs.writeFileSync(manifestPath, JSON.stringify({ exposes, moduleMap }, null, 2))

  console.log(`[Federation] Generated ${Object.keys(exposes).length} wrappers`)

  return exposes
}

module.exports = { getExposes }
